from __future__ import annotations

from collections import defaultdict
from typing import Iterable

import streamlit as st


SECTION_COPY: dict[str, dict[str, str]] = {
    "overview": {
        "title": "Overview",
        "intro": (
            "This app is a review workspace for stock signals. Tomorrow's Picks is the fast shortlist for what to inspect next. "
            "Backtesting Lab is the validation surface for checking how the same ideas behaved historically."
        ),
    },
    "tomorrow": {
        "title": "Tomorrow's Picks",
        "intro": (
            "This page is optimized for quick daily review. It helps you rank candidate signals, inspect one stock in detail, "
            "and see the reasons a row looks strong or weak before you move into a deeper decision workflow."
        ),
    },
    "scores": {
        "title": "Scores And Filters",
        "intro": (
            "The app carries more than one score because they answer different questions. Some scores are heuristic and component-based, "
            "while others summarize historical behavior or estimated stop risk."
        ),
    },
    "patterns": {
        "title": "Pattern Families",
        "intro": (
            "Pattern families A through G represent different setup types. The family label tells you what kind of structure triggered the row, "
            "while the detailed pattern name tells you the specific rule variant."
        ),
    },
    "lab": {
        "title": "Backtesting Lab",
        "intro": (
            "Backtesting Lab is where you stress-test filters, stops, targets, and score behavior. It is designed for evaluating recorded signals, "
            "not for placing trades automatically."
        ),
    },
    "trade_records": {
        "title": "Trade Records",
        "intro": (
            "Trade Records is the main drill-down table in Backtesting Lab. It shows one simulated trade row per signal after the current filters, "
            "including entry, stop, status, returns, and score components."
        ),
    },
    "manual_positions": {
        "title": "Manual Positions",
        "intro": (
            "Manual positions let you track trades or ideas that you want to monitor in the same workspace even if they were not generated by the current daily signal run."
        ),
    },
    "past_results": {
        "title": "Past Results",
        "intro": (
            "Past Results is the quick historical snapshot for a single stock on Tomorrow's Picks. It evaluates a small tail of earlier signals using a simple hold window so you can see recent behavior quickly."
        ),
    },
    "scoring_formula": {
        "title": "Score Formula",
        "intro": (
            "The signal score is a transparent, weighted combination of five independent quality measures. "
            "Understanding how each component is built helps you interpret where a score comes from and why it changes. "
            "After the base weighted sum, two additive bonuses can raise the total above the raw component floor."
        ),
    },
    "enhancers": {
        "title": "Candle Enhancers",
        "intro": (
            "Candle enhancers are optional single-bar or two-bar shape patterns that add a small bonus to the base signal score "
            "when a recognizable candlestick formation appears near the signal date. "
            "The combined enhancer bonus is capped so candle overlays cannot dominate the overall score. "
            "Each enhancer fires independently — two reinforcing shapes on the same bar compound the bonus up to the cap."
        ),
    },
    "workflow": {
        "title": "Daily Workflow",
        "intro": (
            "The engine runs a sequential pipeline every day: update prices, scan all patterns, recompute family weights, "
            "and optionally rebuild the stop risk model. Understanding the pipeline helps you know which data files are "
            "authoritative, when outputs are stale, and which scripts to run if something needs refreshing manually."
        ),
    },
}


HELP_ITEMS: dict[str, dict[str, str]] = {
    "overview": {
        "section": "overview",
        "label": "What this app does",
        "summary": "A quick explanation of the two main pages and how they fit together.",
        "detail": (
            "Use **Tomorrow's Picks** to decide what deserves chart review next. Use **Backtesting Lab** to test how similar signals behaved under a chosen target, stop, and filter set."
        ),
    },
    "tomorrow_picks": {
        "section": "tomorrow",
        "label": "Tomorrow's Picks",
        "summary": "The daily shortlist of candidate signals to review for the next session.",
        "detail": (
            "Tomorrow's Picks ranks the currently relevant signals, applies the selected score method, and lets you inspect one row in detail. "
            "It is meant to reduce the number of names you need to review manually, not replace the review itself."
        ),
    },
    "scoring_method": {
        "section": "scores",
        "label": "Scoring method",
        "summary": "Chooses which ranking measure drives the Tomorrow's Picks list.",
        "detail": (
            "The selected scoring method controls the main ranking number in Tomorrow's Picks. Use **Heuristic score** when you want the component-based quality estimate, "
            "**Reliability score** when you want a more empirical confidence read, and **Stop risk** when you want to focus on downside distance rather than upside quality."
        ),
    },
    "heuristic_score": {
        "section": "scores",
        "label": "Heuristic score",
        "summary": "A composite quality score built from setup, trend, volume, risk, and supporting bonuses.",
        "detail": (
            "Heuristic score is a weighted summary of setup quality. Higher usually means the setup aligns better with the scoring model, but it does not guarantee a profitable trade."
        ),
    },
    "reliability_score": {
        "section": "scores",
        "label": "Reliability score",
        "summary": "A score intended to reflect how trustworthy the signal looks based on learned behavior.",
        "detail": (
            "Reliability score is useful when you want the ranking to emphasize historical consistency more than raw pattern shape. Treat it as a confidence hint, not a promise."
        ),
    },
    "stop_risk": {
        "section": "scores",
        "label": "Stop risk",
        "summary": "An estimate of downside distance between the entry and the stop.",
        "detail": (
            "Stop risk is shown as a percentage-like risk measure. Lower is generally better because it implies a tighter stop relative to the entry."
        ),
    },
    "min_score_filter": {
        "section": "scores",
        "label": "Min score",
        "summary": "Filters out weaker rows based on the currently selected score or lab score threshold.",
        "detail": (
            "In Tomorrow's Picks, the score filter keeps only rows above the chosen score threshold for the active ranking method. In Backtesting Lab, Min score trims the simulated trade set before you evaluate the tracker results."
        ),
    },
    "sort_order": {
        "section": "scores",
        "label": "Sort order",
        "summary": "Chooses how the visible list is ordered after filters are applied.",
        "detail": (
            "Use sort order to decide whether you want the strongest names first, the lowest-risk names first, or a simple alphabetical view. Sorting does not change the underlying rows, only the view."
        ),
    },
    "score_breakdown": {
        "section": "scores",
        "label": "Score breakdown",
        "summary": "The running explanation of why a selected signal earned its score.",
        "detail": (
            "Score breakdown is meant to answer the question: **why is this row scoring where it is?** It decomposes the row into setup, trend, volume, risk, RSI, and any learned bonuses."
        ),
    },
    "overview_metrics": {
        "section": "scores",
        "label": "Overview metrics",
        "summary": "The compact entry, stop, risk, and score summary for the selected signal.",
        "detail": (
            "These are the first numbers to sanity-check on a selected signal. Entry and stop frame the trade. Risk shows the downside distance. The displayed score depends on the currently active ranking method."
        ),
    },
    "entry_price": {
        "section": "scores",
        "label": "Entry price",
        "summary": "The reference buy price used for the signal or simulated trade.",
        "detail": (
            "Entry price is the price used as the starting point for risk and return calculations. In the lab, it feeds position sizing, target price, and PnL."
        ),
    },
    "stop_price": {
        "section": "scores",
        "label": "Stop price",
        "summary": "The protective exit level used to cap downside risk.",
        "detail": (
            "Stop price is the level where the trade is considered invalid or risk control takes over. It is central to both trade risk and stop-hit status."
        ),
    },
    "trade_risk": {
        "section": "scores",
        "label": "Risk",
        "summary": "The percentage distance from entry price to stop price.",
        "detail": (
            "Risk is typically the percent gap between entry and stop. Wider risk may demand smaller position size, while tighter risk can improve capital efficiency if the setup quality still holds."
        ),
    },
    "quick_check": {
        "section": "tomorrow",
        "label": "Quick check",
        "summary": "A fast checklist for trend, breakout posture, volume, stretch, and stop width.",
        "detail": (
            "Quick check is a simplified quality screen for the selected stock. It answers a few high-value questions quickly before you decide whether the chart deserves more attention."
        ),
    },
    "status": {
        "section": "trade_records",
        "label": "Status",
        "summary": "The current or final outcome label for the simulated trade row.",
        "detail": (
            "Typical status values distinguish rows that hit target, hit stop, are still holding, or were tracked under a specific outcome rule. Always interpret status alongside exit date and return."
        ),
    },
    "past_results": {
        "section": "past_results",
        "label": "Past results",
        "summary": "A recent-history check for earlier signals on the same stock.",
        "detail": (
            "Past Results uses a simple evaluation window over recent historical rows for the selected stock. It is not the full Backtesting Lab, but a quick way to see whether the name has behaved cleanly lately."
        ),
    },
    "hold_days": {
        "section": "past_results",
        "label": "Hold days",
        "summary": "How many forward trading days the simple past-results evaluator allows before timing out.",
        "detail": (
            "Hold days controls the evaluation window in the quick Past Results view. Larger values give trades more time to work, while smaller values force a tighter review horizon."
        ),
    },
    "outcome": {
        "section": "past_results",
        "label": "Outcome",
        "summary": "The summarized result of a historical signal after applying the simple evaluation rule.",
        "detail": (
            "Outcome translates the raw evaluation result into plain language such as stopped out, held to end, timed exit, or no future data."
        ),
    },
    "return_pct": {
        "section": "trade_records",
        "label": "Return %",
        "summary": "Percentage return on the simulated trade from entry to current or exit value.",
        "detail": (
            "Return % shows the percent gain or loss produced by the trade row. In open trades it may be marked to the latest close, while in closed trades it reflects the exit outcome."
        ),
    },
    "exit_date": {
        "section": "trade_records",
        "label": "Exit date",
        "summary": "The date the simulated trade closed or reached its evaluated end state.",
        "detail": (
            "Exit date is when the tracker considered the row finished. If the trade is still open, exit date may be blank."
        ),
    },
    "learned_pattern_weights": {
        "section": "patterns",
        "label": "Learned pattern weights",
        "summary": "Historical weights assigned to pattern families based on past signal behavior.",
        "detail": (
            "Learned pattern weights describe how much each pattern family contributes as a bonus or penalty in the scoring system. They come from historical signal behavior and should be treated as model inputs, not standalone signals."
        ),
    },
    "pattern_family": {
        "section": "patterns",
        "label": "Pattern family",
        "summary": "The high-level setup family, such as A through G.",
        "detail": (
            "Pattern family groups signals by setup archetype. The family tells you the broad structure, while the detailed pattern field tells you the specific rule that fired."
        ),
    },
    "pattern": {
        "section": "patterns",
        "label": "Pattern",
        "summary": "The exact rule variant that generated the signal.",
        "detail": (
            "Pattern is the fine-grained label for the trigger logic. It lets you separate broad family behavior from a specific setup flavor."
        ),
    },
    "pattern_score_100": {
        "section": "patterns",
        "label": "Score /100",
        "summary": "A normalized pattern-quality score used in the learned pattern-weight table.",
        "detail": (
            "Score /100 summarizes historical pattern quality on a 0 to 100 scale. It is one input into the final pattern-family weight rather than a live trade score by itself."
        ),
    },
    "pattern_weight_30": {
        "section": "patterns",
        "label": "Weight /30",
        "summary": "The effective bonus or penalty budget allocated to that pattern family.",
        "detail": (
            "Weight /30 is the pattern-family contribution applied in scoring. Larger positive values mean the family earned more trust from the training history."
        ),
    },
    "count": {
        "section": "patterns",
        "label": "Count",
        "summary": "How many historical rows contributed to the learned statistic.",
        "detail": (
            "Count matters because a good-looking edge from very few samples is weaker evidence than a similar edge from a deeper history."
        ),
    },
    "win_rate": {
        "section": "patterns",
        "label": "Win rate",
        "summary": "The share of qualifying trades that ended as wins under the chosen historical definition.",
        "detail": (
            "Win rate is useful for context, but it should be read together with sample count and average returns rather than in isolation."
        ),
    },
    "loss_rate": {
        "section": "patterns",
        "label": "Loss rate",
        "summary": "The share of qualifying trades that ended as losses.",
        "detail": (
            "Loss rate complements win rate and helps you judge whether an attractive pattern score is backed by balanced historical behavior."
        ),
    },
    "edge_pp": {
        "section": "patterns",
        "label": "Edge pp",
        "summary": "The win-rate edge measured in percentage points over baseline.",
        "detail": (
            "Edge pp shows how far a pattern's observed behavior sits above or below a baseline. Positive values suggest historical improvement; negative values suggest drag."
        ),
    },
    "analysis_setup": {
        "section": "lab",
        "label": "Analysis Setup",
        "summary": "The section where you choose scope, stops, targets, and visible record filters for the lab.",
        "detail": (
            "Analysis Setup defines the simulated environment before you study results. The chosen signal families, stop rules, targets, and visible filters all change the trade set you evaluate."
        ),
    },
    "target_pct": {
        "section": "lab",
        "label": "Target %",
        "summary": "The profit target used by the lab simulation.",
        "detail": (
            "Target % defines how much upside the tracker waits for before calling a trade a target hit. Tight targets usually increase hit frequency and reduce per-trade payoff."
        ),
    },
    "stop_mode": {
        "section": "lab",
        "label": "Stop mode",
        "summary": "The rule used to derive or interpret the stop in the lab simulation.",
        "detail": (
            "Stop mode changes how the stop is set or enforced. Some modes use a fixed percentage, others use ATR or structure, and some high-score modes hold to target while keeping the stop only for risk display."
        ),
    },
    "capital_per_trade": {
        "section": "lab",
        "label": "Capital per trade",
        "summary": "The notional capital allocated to each simulated trade row.",
        "detail": (
            "Capital per trade determines the simulated position size in rupee terms. It affects invested amount, quantity, current value, and PnL."
        ),
    },
    "model_reference": {
        "section": "lab",
        "label": "Model and reference controls",
        "summary": "Settings that change which historical rows are evaluated or how reference artifacts are read.",
        "detail": (
            "These controls decide how the lab should interpret saved signal history and evaluation windows. They are for validation and comparison, not for changing the saved production artifacts from inside the UI."
        ),
    },
    "summary_kpis": {
        "section": "lab",
        "label": "Summary KPIs",
        "summary": "The headline counts and returns for the currently visible trade set.",
        "detail": (
            "Summary KPIs are the first stop in Backtesting Lab. Read them before drilling into individual rows so you know whether the current filter set is improving or weakening the overall profile."
        ),
    },
    "trade_records": {
        "section": "trade_records",
        "label": "Trade Records",
        "summary": "The main simulated-trade table for the current lab configuration.",
        "detail": (
            "Trade Records shows the row-level evidence behind the KPI layer. It is where you inspect single trades, compare exits, and verify that a score threshold or stop rule is behaving the way you expect."
        ),
    },
    "qty": {
        "section": "trade_records",
        "label": "Quantity",
        "summary": "The number of shares or units allocated by the capital-per-trade rule.",
        "detail": (
            "Quantity is derived from the entry price and the configured capital per trade. It lets the tracker convert percentage outcomes into invested value and PnL."
        ),
    },
    "invested": {
        "section": "trade_records",
        "label": "Invested",
        "summary": "The actual notional capital committed to that simulated trade row.",
        "detail": (
            "Invested is the position value at entry after quantity is calculated. It may differ slightly from the raw capital-per-trade input because quantity is discrete."
        ),
    },
    "target_price": {
        "section": "trade_records",
        "label": "Target price",
        "summary": "The price level corresponding to the chosen target percentage.",
        "detail": (
            "Target price is the level that marks a target hit under the active target rule."
        ),
    },
    "latest_close": {
        "section": "trade_records",
        "label": "Latest close",
        "summary": "The latest available close used to mark open positions.",
        "detail": (
            "Latest close is used to estimate current value and open-trade return when a row has not yet reached an exit condition."
        ),
    },
    "current_value": {
        "section": "trade_records",
        "label": "Current value",
        "summary": "The marked-to-market value of the simulated position.",
        "detail": (
            "Current value reflects what the position would be worth using the latest available close. For closed trades it should align with the exit state."
        ),
    },
    "pnl": {
        "section": "trade_records",
        "label": "PnL",
        "summary": "Profit or loss in currency terms for the simulated trade row.",
        "detail": (
            "PnL converts the trade outcome into currency terms using invested value and quantity. It is useful when comparing economic impact rather than only percentage performance."
        ),
    },
    "days_held": {
        "section": "trade_records",
        "label": "Days held",
        "summary": "The number of trading days the simulated trade remained active.",
        "detail": (
            "Days held helps you see whether a setup is working quickly or tying up capital for a long time."
        ),
    },
    "score_pattern": {
        "section": "trade_records",
        "label": "Pattern score",
        "summary": "The pattern-specific contribution to the signal score.",
        "detail": (
            "Pattern score reflects how the triggering family or setup contributes to the overall scoring model."
        ),
    },
    "pattern_bonus": {
        "section": "trade_records",
        "label": "Pattern bonus",
        "summary": "The learned family-level bonus or penalty added to the score.",
        "detail": (
            "Pattern bonus comes from the learned pattern-weight artifact. It adjusts the score based on how that family has behaved historically."
        ),
    },
    "stock_rs20": {
        "section": "trade_records",
        "label": "Stock RS20",
        "summary": "The stock's relative strength reading versus the benchmark over roughly 20 trading days.",
        "detail": (
            "RS20 helps show whether the stock is outperforming the benchmark over a shorter window. Stronger relative strength can support trend-following setups."
        ),
    },
    "stock_rs50": {
        "section": "trade_records",
        "label": "Stock RS50",
        "summary": "The stock's relative strength reading versus the benchmark over roughly 50 trading days.",
        "detail": (
            "RS50 is the slower relative-strength companion to RS20 and helps confirm whether a shorter burst is part of a broader outperformance trend."
        ),
    },
    "rs_bonus": {
        "section": "trade_records",
        "label": "RS bonus",
        "summary": "The score bonus added when benchmark-relative strength is enabled and supportive.",
        "detail": (
            "RS bonus is a capped overlay. It nudges the score higher when the stock shows benchmark outperformance and the feature is enabled."
        ),
    },
    "enhancer_bonus": {
        "section": "trade_records",
        "label": "Enhancer bonus",
        "summary": "The extra score assigned from candle-shape enhancer rules.",
        "detail": (
            "Enhancer bonus is the optional overlay from candle-based enhancers such as doji, hammer, or morning star. It is capped so candle overlays do not dominate the base score."
        ),
    },
    "manual_positions": {
        "section": "manual_positions",
        "label": "Manual positions",
        "summary": "The table of user-tracked positions that live alongside the auto-generated lab rows.",
        "detail": (
            "Manual positions let you add your own rows to the review workspace. Use them for discretionary trades, paper trades, or ideas you want to watch outside the generated signal set."
        ),
    },
    "created_at": {
        "section": "manual_positions",
        "label": "Created at",
        "summary": "When the manual row was added to the workspace.",
        "detail": (
            "Created at is the timestamp for when you recorded the manual position in the UI."
        ),
    },
    "source_signal_date": {
        "section": "manual_positions",
        "label": "Source signal date",
        "summary": "The original signal date associated with the row, if you know it.",
        "detail": (
            "Source signal date helps keep a manual position linked back to the original idea or recommendation date."
        ),
    },
    "capital": {
        "section": "manual_positions",
        "label": "Capital",
        "summary": "The manual notional capital assigned to that row.",
        "detail": (
            "Capital determines the notional size of the manual position for current-value and PnL calculations."
        ),
    },
    "current_return_pct": {
        "section": "manual_positions",
        "label": "Current return %",
        "summary": "The marked-to-market percentage return of the manual position.",
        "detail": (
            "Current return % shows how the manual position is performing relative to the recorded entry price."
        ),
    },
    "distance_to_stop_pct": {
        "section": "manual_positions",
        "label": "Distance to stop %",
        "summary": "How close the current price is to the stop, expressed as a percentage.",
        "detail": (
            "Distance to stop % is useful for prioritizing attention. Smaller values mean the position is closer to the protective stop."
        ),
    },
    "note": {
        "section": "manual_positions",
        "label": "Note",
        "summary": "Free-form context about the manual position.",
        "detail": (
            "Use Note for reminders, discretionary context, or anything that makes the row easier to interpret later."
        ),
    },
    # ── Scoring formula components ────────────────────────────────────────────
    "score_trend_comp": {
        "section": "scoring_formula",
        "label": "Trend component (T)",
        "summary": "Measures how strongly the stock is trending at signal time.",
        "detail": (
            "T = clip(50 + trend\\_strength\\_pct × 5). A flat trend lands around 50. Strong upward trend "
            "pushes T toward 100. This weight is **0.20** in the total score, contributing up to 20 points. "
            "The trend strength percent is derived from the relationship between current price, key moving averages, and recent slope."
        ),
    },
    "score_setup_comp": {
        "section": "scoring_formula",
        "label": "Setup component (S)",
        "summary": "Measures how cleanly the specific pattern conditions align.",
        "detail": (
            "S = clip(50 + setup\\_strength\\_pct × 8). Setup quality captures how well the trigger conditions are met — "
            "not just that they fired, but how convincingly. This weight is **0.20**, contributing up to 20 points. "
            "A fresh breakout on high-conviction conditions scores higher than a borderline trigger."
        ),
    },
    "score_volume_comp": {
        "section": "scoring_formula",
        "label": "Volume component (V)",
        "summary": "Measures how much volume exceeds the baseline average on the signal day.",
        "detail": (
            "V = clip(40 + volume\\_ratio × 20). A volume ratio of 1.0 means volume exactly matched the 20-day average. "
            "The baseline 40 ensures a modestly above-average volume day already scores reasonably. "
            "This weight is **0.13**, worth up to 13 points."
        ),
    },
    "score_risk_comp": {
        "section": "scoring_formula",
        "label": "Risk component (R)",
        "summary": "Rewards tighter stops — lower stop distance means higher risk score.",
        "detail": (
            "R = clip(100 − stop\\_pct × 6). A tighter stop distance translates directly to a higher R value. "
            "This weight is **0.14**, worth up to 14 points. R is not a measure of probability — "
            "it is purely a reward for capital efficiency. A 5% stop yields R = 70; a 10% stop yields R = 40."
        ),
    },
    "score_rsi_comp": {
        "section": "scoring_formula",
        "label": "RSI component (I)",
        "summary": "Incorporates the RSI reading at signal time as a minor momentum context.",
        "detail": (
            "I = RSI value (0–100), or 50 if not available. This weight is **0.03** — the smallest component, "
            "contributing at most 3 points. It adds a mild boost when RSI is healthy (e.g. 60–70) "
            "and a mild drag when RSI is very overbought (>80) or very depressed (<30)."
        ),
    },
    "ma_slope_bonus": {
        "section": "scoring_formula",
        "label": "MA slope bonus",
        "summary": "An additive bonus that rewards an accelerating 50-day moving average.",
        "detail": (
            "MA slope bonus = min(3.0, slope\\_pct × 4.0). It is computed from the percentage change in SMA50 "
            "over the last 5 trading days. A rising SMA50 adds up to **3 extra points** on top of the weighted sum. "
            "A flat or declining SMA50 adds zero. This bonus is applied after the five-component base score is assembled."
        ),
    },
    "consensus_bonus": {
        "section": "scoring_formula",
        "label": "Consensus bonus",
        "summary": "Extra credit added when two or more pattern families fire on the same stock and date.",
        "detail": (
            "When multiple pattern families trigger simultaneously on the same ticker and signal date, "
            "the engine can add a consensus bonus because independent methods agreeing on the same setup "
            "is stronger evidence than a single-method trigger. "
            "The size of the bonus depends on the number of agreeing families. "
            "This bonus compounds with the pattern-family weight and MA slope bonus."
        ),
    },
    "pattern_family_bonus_formula": {
        "section": "scoring_formula",
        "label": "Pattern family bonus (B_pattern)",
        "summary": "The learned family contribution — up to 30 points from pattern_weights.json.",
        "detail": (
            "B\\_pattern comes from the learned `pattern_weights.json` artifact. "
            "The formula is approximately: B\\_pattern = (family\\_score / 100) × 30. "
            "So a family with a historical score of 80 contributes roughly 24 extra points. "
            "A family with score 50 contributes 15, and score 0 contributes nothing. "
            "Negative-scoring families can also reduce the score. "
            "This is the largest single bonus and the primary mechanism for differentiating families."
        ),
    },
    "penalty_weights": {
        "section": "scores",
        "label": "Signal penalty weights",
        "summary": "Per-ticker penalties that reduce scores for stocks that have recently underperformed.",
        "detail": (
            "Signal penalty weights are learned per-ticker adjustments stored in `signal_penalty_weights.json`. "
            "When a stock has a history of signaling but not delivering, its penalty weight nudges its score down. "
            "Penalties are applied during the scoring phase so the final displayed score already includes them. "
            "Stocks with clean historical behavior are unaffected. This mechanism helps prevent repeated false positives "
            "from dominating the shortlist."
        ),
    },
    "oos_stop_risk": {
        "section": "scores",
        "label": "Walk-forward stop risk (OOS)",
        "summary": "An out-of-sample stop risk prediction produced by the walk-forward evaluation.",
        "detail": (
            "The walk-forward stop risk model trains on rolling monthly windows and produces out-of-sample (OOS) "
            "predictions for each test month. These predictions estimate the expected stop distance for a signal, "
            "independent of the heuristic score. "
            "In Backtesting Lab the OOS filter is applied via an inner merge, meaning only signals that fall within "
            "a month that has a corresponding walk-forward prediction will appear. This is why pre-2024 signals "
            "may not appear in the lab tracker — the walk-forward warmup period has to complete before predictions start."
        ),
    },
    # ── Candle enhancers ──────────────────────────────────────────────────────
    "enhancer_hammer": {
        "section": "enhancers",
        "label": "Hammer",
        "summary": "A single bar with a small body high up and a long lower shadow, optionally with confirmation.",
        "detail": (
            "A hammer has a small real body in the upper portion of the bar's range and a lower shadow at least twice the body length. "
            "The confirmed version requires the shape plus at least two supporting conditions: recent RSI oversold context, "
            "price near recent support, and volume above average. "
            "The shape-only version fires on geometry alone. "
            "The hammer suggests buyers absorbed selling pressure and pushed price back up by the close."
        ),
    },
    "enhancer_inverted_hammer": {
        "section": "enhancers",
        "label": "Inverted Hammer",
        "summary": "A single bar with a small body in the lower portion and a long upper shadow.",
        "detail": (
            "An inverted hammer is the upside-down counterpart to the hammer. The long upper shadow indicates buyers attempted "
            "to push price higher; the return to a lower close shows partial rejection, but in a downtrend this can mark a "
            "tentative reversal. Its enhancer bonus tends to be smaller than the confirmed hammer "
            "because the pattern on its own is weaker evidence."
        ),
    },
    "enhancer_morning_star": {
        "section": "enhancers",
        "label": "Morning Star",
        "summary": "A three-bar reversal: a red candle, a small indecision bar, then a strong green candle.",
        "detail": (
            "Morning Star is a three-candle sequence: a bearish candle, a small-body or doji bar that gaps or sits below, "
            "then a bullish candle that closes well into the first candle's body. "
            "It suggests the sell-off has exhausted and buyers are regaining control. "
            "Because it requires three aligned bars, it is rarer and generally earns a larger enhancer bonus than single-bar shapes."
        ),
    },
    "enhancer_engulfing": {
        "section": "enhancers",
        "label": "Bullish Engulfing",
        "summary": "A green candle whose real body fully engulfs the previous red candle's body.",
        "detail": (
            "Bullish engulfing requires two bars: a red (bearish) candle followed by a green (bullish) candle whose open is "
            "at or below the prior close and whose close is at or above the prior open. "
            "The green bar's body 'engulfs' the prior bar's body. "
            "It signals decisive buyer dominance after a down day and is considered a reliable two-bar reversal signal."
        ),
    },
    "enhancer_harami": {
        "section": "enhancers",
        "label": "Bullish Harami",
        "summary": "A small green candle contained entirely within the prior large red candle.",
        "detail": (
            "Bullish harami is the reverse of engulfing: a large bearish bar is followed by a smaller bullish bar "
            "whose body sits completely inside the prior bar's body. "
            "The pattern suggests the down move is losing momentum. It is generally considered a weaker signal than "
            "bullish engulfing because the small bar needs to be confirmed by subsequent price action."
        ),
    },
    "enhancer_marubozu": {
        "section": "enhancers",
        "label": "Bullish Marubozu",
        "summary": "A near-shadowless green candle showing uniform buyer dominance throughout the session.",
        "detail": (
            "A bullish marubozu opens at or near its low and closes at or near its high, with minimal upper and lower shadows. "
            "It shows that buyers controlled the entire session without giving sellers an opportunity to reassert. "
            "On a signal-day bar this is a strong confirmation that the breakout or pattern trigger had genuine conviction behind it."
        ),
    },
    "enhancer_doji": {
        "section": "enhancers",
        "label": "Dragonfly Doji",
        "summary": "A T-shaped candle with a tiny body at the top and a long lower shadow.",
        "detail": (
            "A dragonfly doji has an open and close that are nearly identical and sit near the high of the range, "
            "while the long lower shadow shows sellers pushed price down but buyers fully recovered by the close. "
            "The geometry requires the lower shadow to be at least 60% of the full range and the upper shadow to be at most 15%. "
            "As an enhancer it adds a small bonus when this shape appears in the lookback window around the signal date."
        ),
    },
    "enhancer_piercing": {
        "section": "enhancers",
        "label": "Piercing Line",
        "summary": "A two-bar reversal where a strong green candle closes above the midpoint of the prior red candle.",
        "detail": (
            "Piercing Line requires two bars: a long bearish candle (body at least 50% of range) followed by a bullish candle "
            "that opens below the prior bar's low and closes above the midpoint of the prior body, but still below the prior open. "
            "The pattern suggests buyers absorbed the full down move and pushed price back into the red body. "
            "True gap-down opens are required in the textbook version, which may make this rarer on cash-market EOD data than the variant."
        ),
    },
    "enhancer_piercing_variant": {
        "section": "enhancers",
        "label": "Piercing Variant",
        "summary": "A practical cash-market adaptation of Piercing Line that relaxes the gap-down open requirement.",
        "detail": (
            "The piercing variant is designed for markets where true gap-down opens after a bearish session are uncommon. "
            "It fires when the current green bar opens near or slightly below the prior close (within 3%) and still closes above "
            "the midpoint of the prior red body. The body-size requirements are also relaxed (25%/20% vs 50%/50%). "
            "It captures the same 'buyers took back mid-body' conviction without demanding a true gap, making it more frequent in practice."
        ),
    },
    "enhancer_belt_hold": {
        "section": "enhancers",
        "label": "Belt Hold",
        "summary": "A single green candle that opens near its low and closes near its high with almost no lower shadow.",
        "detail": (
            "A bullish belt hold opens at or very near the session low (lower shadow ≤ 5% of range) and closes at or very near the high "
            "(upper shadow ≤ 10%), with a large real body (≥ 75% of range). "
            "The standard version also requires the prior candle to be bearish so the belt hold represents a genuine reversal, "
            "not just a continuation of an existing up move. "
            "The name comes from the idea that buyers 'held' control from the open all the way through to the close."
        ),
    },
    "enhancer_three_white_soldiers": {
        "section": "enhancers",
        "label": "Three White Soldiers",
        "summary": "Three consecutive bullish candles, each closing higher, signalling a strong momentum shift.",
        "detail": (
            "Three white soldiers requires three consecutive green bars where each bar has a meaningful body (≥ 50% of range), "
            "each close is higher than the prior close, and the upper shadows are small (≤ 20% of range). "
            "The combined gain across all three bars must also exceed 4%. "
            "When both higher highs and higher closes are required, the pattern shows sustained buying pressure across three sessions. "
            "As an enhancer it provides a strong bonus, but because it requires three aligned bars it fires less often than single-bar shapes."
        ),
    },
    "enhancer_confirmed_hammer_a": {
        "section": "enhancers",
        "label": "Confirmed Hammer + Pattern A",
        "summary": "A hammer shape that coincides with a Pattern A breakout trigger on the same bar.",
        "detail": (
            "This enhancer combines the hammer geometry (small body in upper portion, lower shadow ≥ 2× body) "
            "with the Pattern A breakout trigger firing on the same signal date. "
            "The coincidence of a bullish reversal candle shape and a clean breakout above a prior reference level on the same bar "
            "is treated as a stronger signal than either alone. "
            "If the Pattern A family weight is high, this enhancer can meaningfully push the total score upward."
        ),
    },
    # ── Per-pattern deep dives ────────────────────────────────────────────────
    "pattern_a": {
        "section": "patterns",
        "label": "Pattern A — Trend Breakout",
        "summary": "A stock already in a strong uptrend pushes above a recent high with above-average volume.",
        "detail": (
            "**Conditions:** SMA50 > SMA200, close > SMA50, close > SMA200, close above the prior N-day high close, "
            "volume exceeds the 20-day average by `volume_multiplier` (default 1.5×).\n\n"
            "**Score boosters:** Strong trend strength (T higher when close is well above both MAs), large volume ratio boosts V, "
            "tight stop boosts R, and if SMA50 slope is rising the MA bonus adds up to 3 points.\n\n"
            "**Typical use:** Best for momentum continuation in high-liquidity names that are already performing well relative to peers. "
            "Works strongest in trending market conditions.\n\n"
            "**Known weaknesses:** Breakouts can fail quickly when market sentiment is weak or when the broader index is extended. "
            "On thinly traded stocks, a single high-volume day may be noise rather than institutional activity. "
            "The pattern is also prone to late entries if `breakout_days` is set too long — the breakout reference may already be stretched."
        ),
    },
    "pattern_b": {
        "section": "patterns",
        "label": "Pattern B — Pullback Rebound",
        "summary": "An uptrending stock dips toward its 20-day average and starts bouncing back.",
        "detail": (
            "**Conditions:** SMA50 > SMA200, close still above SMA50, close is within a small buffer of SMA20, "
            "today closes above yesterday by at least a minimum rebound amount, volume is at least mildly supportive.\n\n"
            "**Score boosters:** A tight pullback to SMA20 with quick recovery boosts setup strength. "
            "Moderate volume on the rebound day is sufficient — the bar does not need to be a standout volume day. "
            "Positive SMA50 slope adds the MA bonus.\n\n"
            "**Typical use:** Offers a less-extended entry than Pattern A by waiting for a pause or dip first. "
            "Best for adding to existing positions or entering names that have already proven their trend but are taking a breath.\n\n"
            "**Known weaknesses:** The condition that close stays above SMA50 means the pullback must be shallow. "
            "In a sharper correction, Pattern B won't fire. False signals can appear if the 'pullback' is actually the start of a longer downtrend, "
            "and the SMA50 > SMA200 condition alone cannot confirm trend health in slow-moving markets."
        ),
    },
    "pattern_c": {
        "section": "patterns",
        "label": "Pattern C — MACD Crossover",
        "summary": "The MACD line crosses above its signal line while the broader trend is still healthy.",
        "detail": (
            "**Conditions:** SMA50 > SMA200, MACD line was at or below the signal line on the prior bar "
            "and crosses above it on the current bar, volume above a relaxed threshold.\n\n"
            "**Score boosters:** The crossover gains more setup credit if the cross happens from well below zero "
            "(deeper reset) rather than near the zero line. Volume and trend components still apply normally. "
            "Positive SMA50 slope adds the MA bonus.\n\n"
            "**Typical use:** Captures momentum re-acceleration in names that have already pulled back. "
            "Often fires earlier than Pattern A, before price has made a dramatic breakout bar.\n\n"
            "**Known weaknesses:** MACD crosses are prone to whipsaws in choppy or sideways markets. "
            "A cross near zero is weaker evidence than one that follows a deep correction. "
            "This pattern can also fire on very small momentum moves that have little practical follow-through."
        ),
    },
    "pattern_d": {
        "section": "patterns",
        "label": "Pattern D — RSI Oversold Bounce",
        "summary": "A stock that was oversold on RSI recovers above the threshold while price confirms buyers are back.",
        "detail": (
            "**Conditions:** SMA50 > SMA200, RSI was below the oversold threshold (typically 40) within the last 1–3 bars, "
            "RSI is now back above the threshold and has reclaimed at least 35, improving by a meaningful amount from the prior bar, "
            "price confirms with a close above the previous day's high or a reclaim above SMA20, volume on the reversal day "
            "is at or above the 20-day average, and the close is still near the recent 10-bar swing low.\n\n"
            "**Score boosters:** RSI recovery through 40 adds extra setup strength. "
            "Reversal-day volume well above average further boosts the volume component. "
            "Rebounds very close to the recent swing low earn extra setup credit. Positive SMA50 slope adds the MA bonus.\n\n"
            "**Typical use:** Tries to catch 'washout then bounce' behavior inside a bigger uptrend. "
            "Most useful in strong trend environments where the dip is brief and buyers clearly step in.\n\n"
            "**Known weaknesses:** In the current learned weight history D is one of the weaker families, so it may carry little "
            "or no family bonus. RSI oversold bounces can also be the first leg of a longer breakdown — the SMA uptrend filter "
            "helps reduce this but does not eliminate it. Very fast RSI recoveries can be noise rather than a real reversal."
        ),
    },
    "pattern_e": {
        "section": "patterns",
        "label": "Pattern E — Bollinger Squeeze Breakout",
        "summary": "Volatility contracts to a multi-week low then price breaks out above the upper Bollinger Band.",
        "detail": (
            "**Conditions:** SMA50 > SMA200, Bollinger Band width is at or near a recent multi-bar low (squeeze), "
            "close breaks above the upper Bollinger Band, volume is above average.\n\n"
            "**Score boosters:** A deeper squeeze (lower prior band width) before the breakout earns more setup credit. "
            "Strong above-average volume on the breakout bar drives the volume component higher. "
            "Positive SMA50 slope adds the MA bonus.\n\n"
            "**Typical use:** Best for names that have coiled quietly for several weeks before expanding. "
            "Squeeze breakouts can produce outsized moves because pent-up energy releases quickly.\n\n"
            "**Known weaknesses:** Bollinger Band squeezes can resolve in either direction — the filter requires an upside break, "
            "but a false upside break followed by a reversal is common in choppy environments. "
            "Tight band periods can also produce low-volume breakouts that evaporate quickly."
        ),
    },
    "pattern_f": {
        "section": "patterns",
        "label": "Pattern F — VWAP Reclaim",
        "summary": "Price was trading below a rolling VWAP approximation and snaps back above it on stronger volume.",
        "detail": (
            "**Conditions:** SMA50 > SMA200, previous close was at or below the rolling VWAP approximation, "
            "current close is above the rolling VWAP, volume is above average.\n\n"
            "**Score boosters:** A crisp VWAP cross with strong volume produces the best setup and volume components. "
            "The rolling VWAP on EOD data is an approximation; exact intraday VWAP is not available. "
            "Positive SMA50 slope adds the MA bonus.\n\n"
            "**Typical use:** Best for catching 'buyers took back the line' setups after a brief dip below value. "
            "Often a cleaner-looking setup than MACD or RSI signals because the level is visible on most charts.\n\n"
            "**Known weaknesses:** End-of-day VWAP is an approximation and may not match intraday levels. "
            "On thin-volume sessions the VWAP line can wander, producing unreliable crosses. "
            "A VWAP reclaim in a weakening trend is a false positive risk because the reclaim may fade the next session."
        ),
    },
    "pattern_g": {
        "section": "patterns",
        "label": "Pattern G — VCP Breakout",
        "summary": "A volatility contraction pattern with shrinking pullbacks followed by a high-volume breakout above resistance.",
        "detail": (
            "**Conditions:** Uptrend already in place, at least three pullbacks can be identified from pivot highs, "
            "each pullback is shallower than the one before (contracting volatility), breakout above recent resistance, "
            "volume support on the breakout bar, and relative volume is dry during the contraction phase.\n\n"
            "**Score boosters:** A tighter final contraction (very shallow last base) earns strong setup credit. "
            "A clean high-volume breakout bar drives the volume component strongly. "
            "Positive SMA50 slope adds the MA bonus.\n\n"
            "**Typical use:** The most structure-heavy pattern in the set. Best used for coiled situations "
            "where multiple prior selling waves are clearly getting smaller. "
            "Because it requires a full VCP analysis it fires less frequently than other families.\n\n"
            "**Known weaknesses:** VCP identification is sensitive to parameter choices (pivot detection, contraction thresholds). "
            "The 'breakout above resistance' condition can fire before the pattern is fully complete in fast-moving stocks. "
            "Low-float or index-heavy names may show VCP shapes that are driven by mechanical index rebalancing rather than genuine accumulation."
        ),
    },
    # ── Tag chip glossary ─────────────────────────────────────────────────────
    "tag_uptrend": {
        "section": "tomorrow",
        "label": "Tag: Uptrend",
        "summary": "The stock's 50-day average is above its 200-day average at the signal date.",
        "detail": (
            "The Uptrend chip is present on every signal in Tomorrow's Picks because all pattern families require "
            "SMA50 > SMA200 as a base condition. If this were not true, the signal would not have passed the pattern filter. "
            "It is a reminder that the broader structure was bullish at the time of the trigger."
        ),
    },
    "tag_breakout": {
        "section": "tomorrow",
        "label": "Tag: Breakout",
        "summary": "The pattern name includes 'breakout', suggesting price crossed a prior reference level.",
        "detail": (
            "The Breakout chip appears when the signal's pattern name contains the word 'breakout'. "
            "This covers Pattern A variants that explicitly check for a close above a prior N-day high. "
            "It is a quick visual hint that the setup is a momentum-through-resistance type rather than a pullback or oscillator signal."
        ),
    },
    "tag_volume_ok": {
        "section": "tomorrow",
        "label": "Tag: Volume okay",
        "summary": "The signal's heuristic score is at or above 65, which typically reflects acceptable volume.",
        "detail": (
            "The 'Volume okay' chip is added when the signal's score is at least 65. "
            "Because the volume component (V) feeds directly into the heuristic score with weight 0.13, "
            "a score above this threshold is a rough proxy for the signal having cleared a basic volume quality bar. "
            "It is not a precise volume filter — use the score breakdown to see the exact volume component value."
        ),
    },
    "tag_low_risk": {
        "section": "tomorrow",
        "label": "Tag: Low risk",
        "summary": "The stop distance (risk %) is at or below 7%, suggesting a tight stop relative to entry.",
        "detail": (
            "The 'Low risk' chip appears when the risk percentage (entry-to-stop distance) is at or below 7.0%. "
            "A tighter stop means less capital at risk if the trade fails, and also contributes to a higher risk component (R) in the score. "
            "For sizing purposes, lower risk per trade enables a larger position within a fixed capital-at-risk budget."
        ),
    },
    "tag_rsi_healthy": {
        "section": "tomorrow",
        "label": "Tag: RSI (states)",
        "summary": "The RSI chip shows live RSI state for the selected stock: healthy, cooling, strong, weak, or stretched.",
        "detail": (
            "RSI tags are computed from the latest available close. The states and their bonus effects are:\n\n"
            "- **RSI healthy** (52–68): Momentum is constructive. +3 pts RSI bonus.\n"
            "- **RSI cooling** (45–52): Momentum is tapering after a stronger move. +1 pt.\n"
            "- **RSI strong** (68–78): Momentum is strong; watch for overextension. +1 pt.\n"
            "- **RSI weak** (<45): Momentum is soft for a breakout entry. −5 pts.\n"
            "- **RSI stretched** (>78): Entry may be late; strong pullback risk. −4 pts.\n\n"
            "The bonus is applied to `ui_score` (the displayed score) in real time from price data, "
            "not stored in the CSV signals file."
        ),
    },
    "tag_candle_patterns": {
        "section": "tomorrow",
        "label": "Tag: Candle patterns",
        "summary": "One or more candle-shape enhancers fired on or near the signal date.",
        "detail": (
            "When the enhancer system detects candle shapes (hammer, engulfing, morning star, etc.) in the lookback window "
            "around the signal date, the relevant shape name is appended as a chip. "
            "Multiple shapes can appear simultaneously. The candle chip is teal-coloured to distinguish it from "
            "trend/score chips (green) and caution chips (red/yellow). "
            "See the Candle Enhancers section for a full description of each shape."
        ),
    },
    # ── Lab controls ──────────────────────────────────────────────────────────
    "atr_buffer": {
        "section": "lab",
        "label": "ATR buffer / ATR multiplier",
        "summary": "Controls how far below the swing low or entry the ATR-based stop is placed.",
        "detail": (
            "This slider changes meaning depending on the active stop mode:\n\n"
            "- **Structure + ATR**: The value is an *ATR buffer* added below the recent swing low. "
            "A value of 0.5 means the stop is placed 0.5 × ATR below the structure low. "
            "This keeps the stop below noise while respecting the natural support level.\n\n"
            "- **ATR**: The value is an *ATR multiplier* applied to entry price. "
            "A value of 2.5 means stop = entry − 2.5 × ATR. "
            "Higher values give the trade more room to breathe at the cost of wider risk.\n\n"
            "In both cases the resulting stop is capped by the Fixed stop % so it cannot be wider than you expect."
        ),
    },
    "sort_direction": {
        "section": "lab",
        "label": "Sort direction",
        "summary": "Whether the sort column is ordered from highest to lowest (descending) or lowest to highest (ascending).",
        "detail": (
            "When **Descending** is checked (the default), the highest value of the chosen sort column appears first. "
            "For `signal_score`, `return_pct`, and `pnl` this is almost always what you want. "
            "When unchecked (ascending), the lowest values appear first — useful for inspecting the worst performers "
            "or the most recently dated signals when sorted by `signal_date`."
        ),
    },
    # ── Tomorrow's Picks card meta ────────────────────────────────────────────
    "recommended_date": {
        "section": "tomorrow",
        "label": "Recommended date",
        "summary": "The date the pattern trigger fired, not the intended entry date.",
        "detail": (
            "The recommended date on a stock card is the `signal_date` of the row — when the pattern conditions were met "
            "using end-of-day data. For a next-day entry workflow, the actual entry opportunity would be the trading session "
            "after this date, assuming conditions still look valid on the open. "
            "Older dates in the list mean the signal is a carry-forward from a prior session and should be re-evaluated "
            "against current price before acting."
        ),
    },
    "reason_text": {
        "section": "tomorrow",
        "label": "Reason text",
        "summary": "A short auto-generated sentence summarising the signal's key quality characteristics.",
        "detail": (
            "The reason text is built from the signal score and risk percentage using a template system. "
            "It is not a model-generated analysis — it is a pattern-matched sentence that reflects whether the setup "
            "scored above a threshold, had tight or wide risk, and whether the pattern is a breakout type. "
            "Use it as a quick orientation, not a definitive thesis. "
            "The Score breakdown section gives the actual component values if you want the full picture."
        ),
    },
    # ── Workflow section ──────────────────────────────────────────────────────
    "workflow_universe": {
        "section": "workflow",
        "label": "Stock universe",
        "summary": "The list of tickers the engine watches, stored in universe_tickers.txt.",
        "detail": (
            "The trigger engine reads tickers from `stock_triggers/data/universe_tickers.txt`. "
            "One ticker per line, in Yahoo Finance format (e.g. RELIANCE.NS). "
            "To add or remove a stock, edit this file and re-run the price update step. "
            "The Nifty 50 universe file is also available under `data/stock_universe/ind_nifty50list.csv` "
            "if you want to reset to a known starting set."
        ),
    },
    "workflow_price_update": {
        "section": "workflow",
        "label": "Price update",
        "summary": "Fetches OHLCV history from Yahoo Finance and refreshes prices_eod.csv.",
        "detail": (
            "Run `update_prices_yf.py` (or `update_prices_bhavcopy.py` for NSE Bhavcopy) once per session before building signals. "
            "The script fetches end-of-day OHLCV data and rebuilds `stock_triggers/data/prices_eod.csv`. "
            "All pattern detectors read from this single file, so keeping it current is the most important maintenance step. "
            "Prices from the past three-plus years are retained to support the longer lookback indicators (SMA200, VCP history, etc.)."
        ),
    },
    "workflow_signal_build": {
        "section": "workflow",
        "label": "Signal build",
        "summary": "Scans patterns A–G across all tickers and dates, writing results to signals_all_patterns.csv.",
        "detail": (
            "Run `generate_signals_all_patterns.py` to regenerate the full signal history. "
            "With `--backfill-history` it rescans all available price history. Without flags it processes only the most recent date. "
            "The output `signals_all_patterns.csv` is the primary input for scoring, weight learning, and the Backtesting Lab. "
            "Pattern A also has its own dedicated file via `generate_triggers_pattern_a.py` for backwards compatibility."
        ),
    },
    "workflow_weight_refresh": {
        "section": "workflow",
        "label": "Pattern weight refresh",
        "summary": "Re-learns which pattern families have been performing best and updates the family bonus weights.",
        "detail": (
            "Run `compute_pattern_weights.py` after each signal build to refresh `pattern_weights.json`. "
            "This file records the historical win rate, edge, and score for each family A–G and computes the bonus contribution "
            "each family earns in the scoring model. "
            "If pattern weights are stale, the scoring model may over- or under-credit families that have recently changed in behaviour. "
            "Also run `compute_signal_penalty_weights.py` to refresh per-ticker penalties."
        ),
    },
    "workflow_pipeline": {
        "section": "workflow",
        "label": "One-command pipeline",
        "summary": "run_signal_refresh_pipeline.py chains all the update steps into a single command.",
        "detail": (
            "For a full daily refresh, `run_signal_refresh_pipeline.py --mode daily` runs: "
            "signal penalty weight update → rescore → training history build → stop risk model → "
            "Pattern A file → all-pattern rescore → candle weights → stock scores. "
            "Use `--refresh-prices false` to skip the price download step if you have already updated prices manually. "
            "Use `--recompute-pattern-weights true` to include the family weight refresh in the same pipeline run. "
            "The pipeline writes its results back to the same data files the UI reads, so no further copying is needed."
        ),
    },
    "workflow_stop_risk_model": {
        "section": "workflow",
        "label": "Stop risk model",
        "summary": "A trained model that estimates the probability a given stop distance will hold.",
        "detail": (
            "Run `compute_signal_stop_risk_model.py` to rebuild the stop risk model from the training signal history. "
            "The model uses signal score components as features (or the full score set if `--feature-set scores_only`) "
            "and produces a predicted stop risk value for each signal. "
            "The predictions populate the `reliability_score` and related columns that appear as an alternative ranking method "
            "in Tomorrow's Picks and the lab stop risk filter."
        ),
    },
    "workflow_walk_forward": {
        "section": "workflow",
        "label": "Walk-forward evaluation",
        "summary": "Generates out-of-sample monthly stop risk predictions using a rolling train/test approach.",
        "detail": (
            "Run `evaluate_stop_risk_walk_forward.py --mode walk-forward` to rebuild `stop_risk_walk_forward_monthly.csv`. "
            "The walk-forward method trains on all data up to each month and predicts on the following month (OOS). "
            "A minimum training warmup period must elapse before OOS predictions begin — this is why pre-2024 signals "
            "are excluded from the Backtesting Lab OOS tracker view. "
            "Reducing `--min-train-rows` lowers the warmup requirement and extends the coverage further back, "
            "but at the cost of less training data per fold."
        ),
    },
}


TABLE_HELP_KEYS: dict[str, dict[str, str]] = {
    "pattern_weights": {
        "Pattern": "pattern_family",
        "Score /100": "pattern_score_100",
        "Weight /30": "pattern_weight_30",
        "Count": "count",
        "Win %": "win_rate",
        "Loss %": "loss_rate",
        "Edge pp": "edge_pp",
    },
    "quick_check": {
        "Item": "quick_check",
        "Status": "status",
    },
    "past_results": {
        "signal_date": "source_signal_date",
        "outcome": "outcome",
        "return_pct": "return_pct",
        "exit_date": "exit_date",
    },
    "trade_records": {
        "signal_date": "source_signal_date",
        "ticker": "overview",
        "pattern_family": "pattern_family",
        "pattern": "pattern",
        "entry_price": "entry_price",
        "qty": "qty",
        "invested": "invested",
        "target_price": "target_price",
        "stop_price": "stop_price",
        "latest_close": "latest_close",
        "current_value": "current_value",
        "pnl": "pnl",
        "return_pct": "return_pct",
        "days_held": "days_held",
        "exit_date": "exit_date",
        "status": "status",
        "signal_score": "heuristic_score",
        "score_pattern": "score_pattern",
        "pattern_bonus": "pattern_bonus",
        "sma50_slope_pct": "ma_slope_bonus",
        "ma_slope_bonus": "ma_slope_bonus",
        "stock_rs20": "stock_rs20",
        "stock_rs50": "stock_rs50",
        "rs_bonus": "rs_bonus",
        "enhancer_bonus": "enhancer_bonus",
    },
    "manual_positions": {
        "created_at": "created_at",
        "source_signal_date": "source_signal_date",
        "ticker": "overview",
        "pattern": "pattern",
        "entry_price": "entry_price",
        "stop_price": "stop_price",
        "latest_close": "latest_close",
        "capital": "capital",
        "current_value": "current_value",
        "pnl": "pnl",
        "current_return_pct": "current_return_pct",
        "distance_to_stop_pct": "distance_to_stop_pct",
        "status": "status",
        "note": "note",
    },
}


def get_help_item(help_key: str) -> dict[str, str]:
    return HELP_ITEMS.get(help_key, HELP_ITEMS["overview"])


def _set_docs_focus(help_key: str) -> None:
    item = get_help_item(help_key)
    st.session_state["docs_focus_key"] = help_key
    st.session_state["docs_focus_section"] = item["section"]
    st.session_state["mode"] = "Documentation"


def _ensure_help_chip_css() -> None:
    if st.session_state.get("_docs_chip_css_v6_loaded"):
        return
    st.session_state["_docs_chip_css_v6_loaded"] = True
    st.markdown(
        """
        <style>
        /* Plain HTML anchor chip — zero Streamlit button theming involved.
           Sky-blue translucent ring: visible on both dark and light backgrounds. */
        a.docs-help-chip {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 1.1rem;
            height: 1.1rem;
            border-radius: 50%;
            background: rgba(56, 189, 248, 0.13);
            border: 1.5px solid rgba(56, 189, 248, 0.55);
            color: #38bdf8 !important;
            font-size: 0.64rem;
            font-weight: 900;
            line-height: 1;
            text-decoration: none !important;
            cursor: pointer;
            vertical-align: middle;
            flex-shrink: 0;
            font-family: ui-sans-serif, system-ui, sans-serif;
            letter-spacing: -0.01em;
            transition: background 0.15s, border-color 0.15s, box-shadow 0.15s;
        }
        a.docs-help-chip:hover,
        a.docs-help-chip:focus {
            background: rgba(56, 189, 248, 0.28);
            border-color: #38bdf8;
            color: #7dd3fc !important;
            box-shadow: 0 0 0 2px rgba(56, 189, 248, 0.2);
            text-decoration: none !important;
            outline: none;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def handle_help_query_param() -> None:
    """Call once at top of app — intercepts ?help=<key> clicks from HTML chips."""
    focus = st.query_params.get("help", "")
    if focus and focus in HELP_ITEMS:
        # Remove the param so it doesn't persist across reruns
        params = dict(st.query_params)
        params.pop("help", None)
        st.query_params.from_dict(params)
        _set_docs_focus(focus)
        st.rerun()


def render_help_button(help_key: str, *, key: str, tooltip: str | None = None) -> None:
    _ensure_help_chip_css()
    item = get_help_item(help_key)
    title_text = (tooltip or f"{item['label']}: {item['summary']}").replace('"', "&quot;").replace("'", "&#39;")
    st.markdown(
        f'<a class="docs-help-chip" href="?help={help_key}" title="{title_text}">?</a>',
        unsafe_allow_html=True,
    )


def render_heading_with_help(
    title: str,
    help_key: str,
    *,
    key: str,
    level: int = 3,
    caption: str | None = None,
) -> None:
    left, right = st.columns([0.94, 0.06])
    with left:
        st.markdown(f"{'#' * int(level)} {title}")
    with right:
        render_help_button(help_key, key=key)
    if caption:
        st.caption(caption)


def render_caption_with_help(text: str, help_key: str, *, key: str) -> None:
    left, right = st.columns([0.9, 0.1], gap="small")
    with left:
        st.markdown(
            f"<div style='font-size:0.78rem; color:var(--heading-color); font-weight:700; line-height:1.15;'>{text}</div>",
            unsafe_allow_html=True,
        )
    with right:
        render_help_button(help_key, key=key)


def table_help_map(table_name: str, columns: Iterable[str]) -> dict[str, str]:
    table_map = TABLE_HELP_KEYS.get(table_name, {})
    return {column: table_map[column] for column in columns if column in table_map}


def build_dataframe_column_config(column_help_keys: dict[str, str]) -> dict[str, object]:
    config: dict[str, object] = {}
    for column, help_key in column_help_keys.items():
        item = get_help_item(help_key)
        config[column] = st.column_config.Column(column, help=item["summary"])
    return config


def render_table_help_glossary(
    title: str,
    column_help_keys: dict[str, str],
    *,
    key_prefix: str,
    expanded: bool = False,
) -> None:
    if not column_help_keys:
        return

    with st.expander(f"{title} column help", expanded=expanded):
        for idx, (column, help_key) in enumerate(column_help_keys.items()):
            item = get_help_item(help_key)
            left, right = st.columns([0.88, 0.12])
            with left:
                st.markdown(f"**{column}**  \\n+{item['summary']}")
            with right:
                render_help_button(help_key, key=f"{key_prefix}_{idx}")


def _pattern_family_lines() -> list[str]:
    return [
        "**A**: breakout-style setups that rely on strength through a prior reference zone.",
        "**B**: alternate breakout or continuation behavior with a different trigger shape.",
        "**C**: MACD-oriented setups that look for momentum confirmation.",
        "**D**: RSI-oriented setups that look for strength and reset behavior.",
        "**E**: Bollinger-style setups that use band structure or compression clues.",
        "**F**: VWAP-oriented setups that care about price behavior around intraday or anchored reference value.",
        "**G**: VCP-style contraction and breakout setups.",
    ]


def _render_score_formula() -> None:
    st.markdown(
        "The five independent components are weighted and summed into a base score:"
    )
    st.latex(
        r"\text{Score}_{\text{base}} = \underbrace{0.20\,T}_{\text{Trend}}"
        r"+ \underbrace{0.20\,S}_{\text{Setup}}"
        r"+ \underbrace{0.13\,V}_{\text{Volume}}"
        r"+ \underbrace{0.14\,R}_{\text{Risk}}"
        r"+ \underbrace{0.03\,I}_{\text{RSI}}"
    )
    col1, col2 = st.columns(2)
    with col1:
        st.markdown(
            "**Component ranges (each clipped 0–100)**\n\n"
            "- **T** = clip(50 + trend\\_pct × 5)\n"
            "- **S** = clip(50 + setup\\_pct × 8)\n"
            "- **V** = clip(40 + volume\\_ratio × 20)\n"
            "- **R** = clip(100 − stop\\_pct × 6)\n"
            "- **I** = RSI value, or 50 if unavailable"
        )
    with col2:
        st.markdown(
            "**Additive bonuses applied after base score**\n\n"
            "- **B_pattern** — learned family bonus up to +30 pts\n"
            "- **B_slope** — SMA50 acceleration bonus, capped +3 pts\n"
            "- **B_consensus** — multi-family agreement bonus\n\n"
            "Final score = clip(Score_base + B_pattern + B_slope + B_consensus, 0, 100)"
        )
    st.caption(
        "Weight breakdown: Trend 20 pts · Setup 20 pts · Volume 13 pts · Risk 14 pts · RSI 3 pts · Pattern ≤30 pts · Slope ≤3 pts."
    )


# Preferred display order within key sections (unlisted items fall back to alpha)
SECTION_ITEM_ORDER: dict[str, list[str]] = {
    "scores": [
        "heuristic_score", "reliability_score", "stop_risk",
        "min_score_filter", "sort_order", "overview_metrics",
        "entry_price", "stop_price", "trade_risk",
        "score_breakdown",
        "penalty_weights", "oos_stop_risk",
    ],
    "scoring_formula": [
        "score_trend_comp", "score_setup_comp", "score_volume_comp",
        "score_risk_comp", "score_rsi_comp",
        "ma_slope_bonus", "pattern_family_bonus_formula", "consensus_bonus",
    ],
    "patterns": [
        "pattern_a", "pattern_b", "pattern_c", "pattern_d",
        "pattern_e", "pattern_f", "pattern_g",
        "pattern_family", "pattern", "learned_pattern_weights",
        "pattern_score_100", "pattern_weight_30",
        "count", "win_rate", "loss_rate", "edge_pp",
    ],
    "lab": [
        "analysis_setup",
        "target_pct", "stop_mode", "atr_buffer",
        "capital_per_trade", "min_score_filter",
        "sort_order", "sort_direction",
        "summary_kpis", "model_reference",
    ],
    "trade_records": [
        "status", "return_pct", "pnl", "days_held", "exit_date",
        "entry_price", "stop_price", "target_price",
        "qty", "invested", "current_value", "latest_close",
        "score_pattern", "pattern_bonus",
        "stock_rs20", "stock_rs50", "rs_bonus", "enhancer_bonus",
    ],
    "tomorrow": [
        "tomorrow_picks", "scoring_method",
        "recommended_date", "reason_text",
        "tag_uptrend", "tag_breakout", "tag_volume_ok",
        "tag_low_risk", "tag_rsi_healthy", "tag_candle_patterns",
        "quick_check",
    ],
    "enhancers": [
        "enhancer_hammer", "enhancer_confirmed_hammer_a",
        "enhancer_marubozu", "enhancer_belt_hold",
        "enhancer_engulfing", "enhancer_harami",
        "enhancer_morning_star", "enhancer_three_white_soldiers",
        "enhancer_piercing", "enhancer_piercing_variant",
        "enhancer_inverted_hammer", "enhancer_doji",
    ],
    "workflow": [
        "workflow_pipeline", "workflow_price_update",
        "workflow_signal_build", "workflow_weight_refresh",
        "workflow_stop_risk_model", "workflow_walk_forward",
        "workflow_universe",
    ],
}


def _sort_section_items(
    section_id: str,
    items: list[tuple[str, dict[str, str]]],
) -> list[tuple[str, dict[str, str]]]:
    """Sort items by SECTION_ITEM_ORDER preference, then alpha for unregistered keys."""
    order = SECTION_ITEM_ORDER.get(section_id, [])
    order_map = {key: idx for idx, key in enumerate(order)}
    return sorted(items, key=lambda pair: (order_map.get(pair[0], 9999), pair[1]["label"]))


def _highlight(text: str, query: str) -> str:
    """Wrap all case-insensitive occurrences of *query* in <strong> tags."""
    if not query:
        return text
    import re
    pattern = re.compile(re.escape(query), re.IGNORECASE)
    return pattern.sub(lambda m: f"**{m.group(0)}**", text)


def render_documentation_page() -> None:
    focus_key = str(st.session_state.get("docs_focus_key", "") or "").strip()
    focus_item = get_help_item(focus_key) if focus_key else None
    focus_section = str(st.session_state.get("docs_focus_section", "") or "").strip()

    st.markdown(
        (
            "<div class='hero'>"
            "<div class='hero-title'>Documentation</div>"
            "<div class='hero-sub'>"
            "Use the <strong>?</strong> chips across the app to jump here for deeper explanations. "
            "Search topics below or expand a section to browse."
            "</div>"
            "</div>"
        ),
        unsafe_allow_html=True,
    )

    # ── Focus card ────────────────────────────────────────────────────────────
    if focus_item:
        section_title = SECTION_COPY.get(focus_item["section"], {}).get("title", "")
        st.markdown(
            f"<div style='background:rgba(56,189,248,0.08);border-left:3px solid #38bdf8;"
            f"padding:0.75rem 1rem 0.75rem 1rem;border-radius:0 4px 4px 0;margin-bottom:1.2rem'>"
            f"<div style='font-size:0.68rem;text-transform:uppercase;letter-spacing:0.1em;"
            f"color:#38bdf8;margin-bottom:0.25rem;font-weight:700'>{section_title}</div>"
            f"<div style='font-size:1rem;font-weight:700;margin-bottom:0.4rem'>{focus_item['label']}</div>"
            f"<div style='font-size:0.88rem;line-height:1.55'>{focus_item['detail']}</div>"
            f"</div>",
            unsafe_allow_html=True,
        )

    # ── Search bar ────────────────────────────────────────────────────────────
    search_query = st.text_input(
        "Search topics",
        value="",
        placeholder="e.g. hammer, stop mode, RSI…",
        key="docs_search",
        label_visibility="collapsed",
    )
    search_q = search_query.strip().lower()

    # ── Section navigation (5 cols × N rows, with item counts) ───────────────
    grouped_items: dict[str, list[tuple[str, dict[str, str]]]] = defaultdict(list)
    for help_key, item in HELP_ITEMS.items():
        grouped_items[item["section"]].append((help_key, item))

    section_ids = list(SECTION_COPY.keys())
    nav_cols = st.columns(5)
    for idx, section_id in enumerate(section_ids):
        count = len(grouped_items.get(section_id, []))
        label = f"{SECTION_COPY[section_id]['title']} ({count})"
        with nav_cols[idx % 5]:
            if st.button(label, key=f"docs_nav_{section_id}", width="stretch"):
                st.session_state["docs_focus_section"] = section_id
                st.session_state["docs_focus_key"] = ""
                st.session_state["docs_search"] = ""
                st.rerun()

    st.markdown("---")

    # ── Build search results ──────────────────────────────────────────────────
    if search_q:
        matched: list[tuple[str, str, dict[str, str]]] = []  # (section_id, help_key, item)
        for help_key, item in HELP_ITEMS.items():
            haystack = f"{item['label']} {item.get('summary','')} {item['detail']}".lower()
            if search_q in haystack:
                matched.append((item["section"], help_key, item))

        if not matched:
            st.info(f"No topics matched **{search_query}**. Try a shorter or different keyword.")
        else:
            st.caption(f"{len(matched)} result{'s' if len(matched) != 1 else ''} for **{search_query}**")
            for section_id, help_key, item in matched:
                section_title = SECTION_COPY.get(section_id, {}).get("title", section_id)
                st.markdown(f"#### {_highlight(item['label'], search_query)}")
                st.caption(f"{section_title}  ·  {_highlight(item.get('summary', ''), search_query)}")
                highlighted_detail = _highlight(item["detail"], search_query)
                st.markdown(highlighted_detail)
                if focus_key == help_key:
                    st.caption("↑ This is the topic you most recently opened from the live UI.")
        return  # Don't render section expanders when searching

    # ── Section expanders ─────────────────────────────────────────────────────
    for section_id, copy in SECTION_COPY.items():
        expanded = section_id == focus_section or bool(
            focus_item and focus_item["section"] == section_id
        )
        with st.expander(copy["title"], expanded=expanded):
            st.markdown(copy["intro"])

            if section_id == "patterns":
                for line in _pattern_family_lines():
                    st.markdown(f"- {line}")

            if section_id == "scoring_formula":
                _render_score_formula()

            items_in_section = _sort_section_items(
                section_id, grouped_items.get(section_id, [])
            )
            for help_key, item in items_in_section:
                st.markdown(f"#### {item['label']}")
                if item.get("summary"):
                    st.caption(item["summary"])
                st.markdown(item["detail"])
                if focus_key == help_key:
                    st.caption("↑ This is the topic you most recently opened from the live UI.")