from __future__ import annotations

from collections import defaultdict
from typing import Iterable

import streamlit as st


SECTION_COPY: dict[str, dict[str, str]] = {
    "overview": {
        "title": "Overview",
        "intro": (
            "This app is a review workspace for stock signals. Tomorrow's Picks is the fast shortlist for what to inspect next. "
            "Backtesting Lab is the validation surface for checking how the same ideas behaved historically."
        ),
    },
    "tomorrow": {
        "title": "Tomorrow's Picks",
        "intro": (
            "This page is optimized for quick daily review. It helps you rank candidate signals, inspect one stock in detail, "
            "and see the reasons a row looks strong or weak before you move into a deeper decision workflow."
        ),
    },
    "scores": {
        "title": "Scores And Filters",
        "intro": (
            "The app carries more than one score because they answer different questions. Some scores are heuristic and component-based, "
            "while others summarize historical behavior or estimated stop risk."
        ),
    },
    "patterns": {
        "title": "Pattern Families",
        "intro": (
            "Pattern families A through G represent different setup types. The family label tells you what kind of structure triggered the row, "
            "while the detailed pattern name tells you the specific rule variant."
        ),
    },
    "lab": {
        "title": "Backtesting Lab",
        "intro": (
            "Backtesting Lab is where you stress-test filters, stops, targets, and score behavior. It is designed for evaluating recorded signals, "
            "not for placing trades automatically."
        ),
    },
    "trade_records": {
        "title": "Trade Records",
        "intro": (
            "Trade Records is the main drill-down table in Backtesting Lab. It shows one simulated trade row per signal after the current filters, "
            "including entry, stop, status, returns, and score components."
        ),
    },
    "manual_positions": {
        "title": "Manual Positions",
        "intro": (
            "Manual positions let you track trades or ideas that you want to monitor in the same workspace even if they were not generated by the current daily signal run."
        ),
    },
    "past_results": {
        "title": "Past Results",
        "intro": (
            "Past Results is the quick historical snapshot for a single stock on Tomorrow's Picks. It evaluates a small tail of earlier signals using a simple hold window so you can see recent behavior quickly."
        ),
    },
}


HELP_ITEMS: dict[str, dict[str, str]] = {
    "overview": {
        "section": "overview",
        "label": "What this app does",
        "summary": "A quick explanation of the two main pages and how they fit together.",
        "detail": (
            "Use **Tomorrow's Picks** to decide what deserves chart review next. Use **Backtesting Lab** to test how similar signals behaved under a chosen target, stop, and filter set."
        ),
    },
    "tomorrow_picks": {
        "section": "tomorrow",
        "label": "Tomorrow's Picks",
        "summary": "The daily shortlist of candidate signals to review for the next session.",
        "detail": (
            "Tomorrow's Picks ranks the currently relevant signals, applies the selected score method, and lets you inspect one row in detail. "
            "It is meant to reduce the number of names you need to review manually, not replace the review itself."
        ),
    },
    "scoring_method": {
        "section": "scores",
        "label": "Scoring method",
        "summary": "Chooses which ranking measure drives the Tomorrow's Picks list.",
        "detail": (
            "The selected scoring method controls the main ranking number in Tomorrow's Picks. Use **Heuristic score** when you want the component-based quality estimate, "
            "**Reliability score** when you want a more empirical confidence read, and **Stop risk** when you want to focus on downside distance rather than upside quality."
        ),
    },
    "heuristic_score": {
        "section": "scores",
        "label": "Heuristic score",
        "summary": "A composite quality score built from setup, trend, volume, risk, and supporting bonuses.",
        "detail": (
            "Heuristic score is a weighted summary of setup quality. Higher usually means the setup aligns better with the scoring model, but it does not guarantee a profitable trade."
        ),
    },
    "reliability_score": {
        "section": "scores",
        "label": "Reliability score",
        "summary": "A score intended to reflect how trustworthy the signal looks based on learned behavior.",
        "detail": (
            "Reliability score is useful when you want the ranking to emphasize historical consistency more than raw pattern shape. Treat it as a confidence hint, not a promise."
        ),
    },
    "stop_risk": {
        "section": "scores",
        "label": "Stop risk",
        "summary": "An estimate of downside distance between the entry and the stop.",
        "detail": (
            "Stop risk is shown as a percentage-like risk measure. Lower is generally better because it implies a tighter stop relative to the entry."
        ),
    },
    "min_score_filter": {
        "section": "scores",
        "label": "Min score",
        "summary": "Filters out weaker rows based on the currently selected score or lab score threshold.",
        "detail": (
            "In Tomorrow's Picks, the score filter keeps only rows above the chosen score threshold for the active ranking method. In Backtesting Lab, Min score trims the simulated trade set before you evaluate the tracker results."
        ),
    },
    "sort_order": {
        "section": "scores",
        "label": "Sort order",
        "summary": "Chooses how the visible list is ordered after filters are applied.",
        "detail": (
            "Use sort order to decide whether you want the strongest names first, the lowest-risk names first, or a simple alphabetical view. Sorting does not change the underlying rows, only the view."
        ),
    },
    "score_breakdown": {
        "section": "scores",
        "label": "Score breakdown",
        "summary": "The running explanation of why a selected signal earned its score.",
        "detail": (
            "Score breakdown is meant to answer the question: **why is this row scoring where it is?** It decomposes the row into setup, trend, volume, risk, RSI, and any learned bonuses."
        ),
    },
    "overview_metrics": {
        "section": "scores",
        "label": "Overview metrics",
        "summary": "The compact entry, stop, risk, and score summary for the selected signal.",
        "detail": (
            "These are the first numbers to sanity-check on a selected signal. Entry and stop frame the trade. Risk shows the downside distance. The displayed score depends on the currently active ranking method."
        ),
    },
    "entry_price": {
        "section": "scores",
        "label": "Entry price",
        "summary": "The reference buy price used for the signal or simulated trade.",
        "detail": (
            "Entry price is the price used as the starting point for risk and return calculations. In the lab, it feeds position sizing, target price, and PnL."
        ),
    },
    "stop_price": {
        "section": "scores",
        "label": "Stop price",
        "summary": "The protective exit level used to cap downside risk.",
        "detail": (
            "Stop price is the level where the trade is considered invalid or risk control takes over. It is central to both trade risk and stop-hit status."
        ),
    },
    "trade_risk": {
        "section": "scores",
        "label": "Risk",
        "summary": "The percentage distance from entry price to stop price.",
        "detail": (
            "Risk is typically the percent gap between entry and stop. Wider risk may demand smaller position size, while tighter risk can improve capital efficiency if the setup quality still holds."
        ),
    },
    "quick_check": {
        "section": "tomorrow",
        "label": "Quick check",
        "summary": "A fast checklist for trend, breakout posture, volume, stretch, and stop width.",
        "detail": (
            "Quick check is a simplified quality screen for the selected stock. It answers a few high-value questions quickly before you decide whether the chart deserves more attention."
        ),
    },
    "status": {
        "section": "trade_records",
        "label": "Status",
        "summary": "The current or final outcome label for the simulated trade row.",
        "detail": (
            "Typical status values distinguish rows that hit target, hit stop, are still holding, or were tracked under a specific outcome rule. Always interpret status alongside exit date and return."
        ),
    },
    "past_results": {
        "section": "past_results",
        "label": "Past results",
        "summary": "A recent-history check for earlier signals on the same stock.",
        "detail": (
            "Past Results uses a simple evaluation window over recent historical rows for the selected stock. It is not the full Backtesting Lab, but a quick way to see whether the name has behaved cleanly lately."
        ),
    },
    "hold_days": {
        "section": "past_results",
        "label": "Hold days",
        "summary": "How many forward trading days the simple past-results evaluator allows before timing out.",
        "detail": (
            "Hold days controls the evaluation window in the quick Past Results view. Larger values give trades more time to work, while smaller values force a tighter review horizon."
        ),
    },
    "outcome": {
        "section": "past_results",
        "label": "Outcome",
        "summary": "The summarized result of a historical signal after applying the simple evaluation rule.",
        "detail": (
            "Outcome translates the raw evaluation result into plain language such as stopped out, held to end, timed exit, or no future data."
        ),
    },
    "return_pct": {
        "section": "trade_records",
        "label": "Return %",
        "summary": "Percentage return on the simulated trade from entry to current or exit value.",
        "detail": (
            "Return % shows the percent gain or loss produced by the trade row. In open trades it may be marked to the latest close, while in closed trades it reflects the exit outcome."
        ),
    },
    "exit_date": {
        "section": "trade_records",
        "label": "Exit date",
        "summary": "The date the simulated trade closed or reached its evaluated end state.",
        "detail": (
            "Exit date is when the tracker considered the row finished. If the trade is still open, exit date may be blank."
        ),
    },
    "learned_pattern_weights": {
        "section": "patterns",
        "label": "Learned pattern weights",
        "summary": "Historical weights assigned to pattern families based on past signal behavior.",
        "detail": (
            "Learned pattern weights describe how much each pattern family contributes as a bonus or penalty in the scoring system. They come from historical signal behavior and should be treated as model inputs, not standalone signals."
        ),
    },
    "pattern_family": {
        "section": "patterns",
        "label": "Pattern family",
        "summary": "The high-level setup family, such as A through G.",
        "detail": (
            "Pattern family groups signals by setup archetype. The family tells you the broad structure, while the detailed pattern field tells you the specific rule that fired."
        ),
    },
    "pattern": {
        "section": "patterns",
        "label": "Pattern",
        "summary": "The exact rule variant that generated the signal.",
        "detail": (
            "Pattern is the fine-grained label for the trigger logic. It lets you separate broad family behavior from a specific setup flavor."
        ),
    },
    "pattern_score_100": {
        "section": "patterns",
        "label": "Score /100",
        "summary": "A normalized pattern-quality score used in the learned pattern-weight table.",
        "detail": (
            "Score /100 summarizes historical pattern quality on a 0 to 100 scale. It is one input into the final pattern-family weight rather than a live trade score by itself."
        ),
    },
    "pattern_weight_30": {
        "section": "patterns",
        "label": "Weight /30",
        "summary": "The effective bonus or penalty budget allocated to that pattern family.",
        "detail": (
            "Weight /30 is the pattern-family contribution applied in scoring. Larger positive values mean the family earned more trust from the training history."
        ),
    },
    "count": {
        "section": "patterns",
        "label": "Count",
        "summary": "How many historical rows contributed to the learned statistic.",
        "detail": (
            "Count matters because a good-looking edge from very few samples is weaker evidence than a similar edge from a deeper history."
        ),
    },
    "win_rate": {
        "section": "patterns",
        "label": "Win rate",
        "summary": "The share of qualifying trades that ended as wins under the chosen historical definition.",
        "detail": (
            "Win rate is useful for context, but it should be read together with sample count and average returns rather than in isolation."
        ),
    },
    "loss_rate": {
        "section": "patterns",
        "label": "Loss rate",
        "summary": "The share of qualifying trades that ended as losses.",
        "detail": (
            "Loss rate complements win rate and helps you judge whether an attractive pattern score is backed by balanced historical behavior."
        ),
    },
    "edge_pp": {
        "section": "patterns",
        "label": "Edge pp",
        "summary": "The win-rate edge measured in percentage points over baseline.",
        "detail": (
            "Edge pp shows how far a pattern's observed behavior sits above or below a baseline. Positive values suggest historical improvement; negative values suggest drag."
        ),
    },
    "analysis_setup": {
        "section": "lab",
        "label": "Analysis Setup",
        "summary": "The section where you choose scope, stops, targets, and visible record filters for the lab.",
        "detail": (
            "Analysis Setup defines the simulated environment before you study results. The chosen signal families, stop rules, targets, and visible filters all change the trade set you evaluate."
        ),
    },
    "target_pct": {
        "section": "lab",
        "label": "Target %",
        "summary": "The profit target used by the lab simulation.",
        "detail": (
            "Target % defines how much upside the tracker waits for before calling a trade a target hit. Tight targets usually increase hit frequency and reduce per-trade payoff."
        ),
    },
    "stop_mode": {
        "section": "lab",
        "label": "Stop mode",
        "summary": "The rule used to derive or interpret the stop in the lab simulation.",
        "detail": (
            "Stop mode changes how the stop is set or enforced. Some modes use a fixed percentage, others use ATR or structure, and some high-score modes hold to target while keeping the stop only for risk display."
        ),
    },
    "capital_per_trade": {
        "section": "lab",
        "label": "Capital per trade",
        "summary": "The notional capital allocated to each simulated trade row.",
        "detail": (
            "Capital per trade determines the simulated position size in rupee terms. It affects invested amount, quantity, current value, and PnL."
        ),
    },
    "model_reference": {
        "section": "lab",
        "label": "Model and reference controls",
        "summary": "Settings that change which historical rows are evaluated or how reference artifacts are read.",
        "detail": (
            "These controls decide how the lab should interpret saved signal history and evaluation windows. They are for validation and comparison, not for changing the saved production artifacts from inside the UI."
        ),
    },
    "summary_kpis": {
        "section": "lab",
        "label": "Summary KPIs",
        "summary": "The headline counts and returns for the currently visible trade set.",
        "detail": (
            "Summary KPIs are the first stop in Backtesting Lab. Read them before drilling into individual rows so you know whether the current filter set is improving or weakening the overall profile."
        ),
    },
    "trade_records": {
        "section": "trade_records",
        "label": "Trade Records",
        "summary": "The main simulated-trade table for the current lab configuration.",
        "detail": (
            "Trade Records shows the row-level evidence behind the KPI layer. It is where you inspect single trades, compare exits, and verify that a score threshold or stop rule is behaving the way you expect."
        ),
    },
    "qty": {
        "section": "trade_records",
        "label": "Quantity",
        "summary": "The number of shares or units allocated by the capital-per-trade rule.",
        "detail": (
            "Quantity is derived from the entry price and the configured capital per trade. It lets the tracker convert percentage outcomes into invested value and PnL."
        ),
    },
    "invested": {
        "section": "trade_records",
        "label": "Invested",
        "summary": "The actual notional capital committed to that simulated trade row.",
        "detail": (
            "Invested is the position value at entry after quantity is calculated. It may differ slightly from the raw capital-per-trade input because quantity is discrete."
        ),
    },
    "target_price": {
        "section": "trade_records",
        "label": "Target price",
        "summary": "The price level corresponding to the chosen target percentage.",
        "detail": (
            "Target price is the level that marks a target hit under the active target rule."
        ),
    },
    "latest_close": {
        "section": "trade_records",
        "label": "Latest close",
        "summary": "The latest available close used to mark open positions.",
        "detail": (
            "Latest close is used to estimate current value and open-trade return when a row has not yet reached an exit condition."
        ),
    },
    "current_value": {
        "section": "trade_records",
        "label": "Current value",
        "summary": "The marked-to-market value of the simulated position.",
        "detail": (
            "Current value reflects what the position would be worth using the latest available close. For closed trades it should align with the exit state."
        ),
    },
    "pnl": {
        "section": "trade_records",
        "label": "PnL",
        "summary": "Profit or loss in currency terms for the simulated trade row.",
        "detail": (
            "PnL converts the trade outcome into currency terms using invested value and quantity. It is useful when comparing economic impact rather than only percentage performance."
        ),
    },
    "days_held": {
        "section": "trade_records",
        "label": "Days held",
        "summary": "The number of trading days the simulated trade remained active.",
        "detail": (
            "Days held helps you see whether a setup is working quickly or tying up capital for a long time."
        ),
    },
    "score_pattern": {
        "section": "trade_records",
        "label": "Pattern score",
        "summary": "The pattern-specific contribution to the signal score.",
        "detail": (
            "Pattern score reflects how the triggering family or setup contributes to the overall scoring model."
        ),
    },
    "pattern_bonus": {
        "section": "trade_records",
        "label": "Pattern bonus",
        "summary": "The learned family-level bonus or penalty added to the score.",
        "detail": (
            "Pattern bonus comes from the learned pattern-weight artifact. It adjusts the score based on how that family has behaved historically."
        ),
    },
    "stock_rs20": {
        "section": "trade_records",
        "label": "Stock RS20",
        "summary": "The stock's relative strength reading versus the benchmark over roughly 20 trading days.",
        "detail": (
            "RS20 helps show whether the stock is outperforming the benchmark over a shorter window. Stronger relative strength can support trend-following setups."
        ),
    },
    "stock_rs50": {
        "section": "trade_records",
        "label": "Stock RS50",
        "summary": "The stock's relative strength reading versus the benchmark over roughly 50 trading days.",
        "detail": (
            "RS50 is the slower relative-strength companion to RS20 and helps confirm whether a shorter burst is part of a broader outperformance trend."
        ),
    },
    "rs_bonus": {
        "section": "trade_records",
        "label": "RS bonus",
        "summary": "The score bonus added when benchmark-relative strength is enabled and supportive.",
        "detail": (
            "RS bonus is a capped overlay. It nudges the score higher when the stock shows benchmark outperformance and the feature is enabled."
        ),
    },
    "enhancer_bonus": {
        "section": "trade_records",
        "label": "Enhancer bonus",
        "summary": "The extra score assigned from candle-shape enhancer rules.",
        "detail": (
            "Enhancer bonus is the optional overlay from candle-based enhancers such as doji, hammer, or morning star. It is capped so candle overlays do not dominate the base score."
        ),
    },
    "manual_positions": {
        "section": "manual_positions",
        "label": "Manual positions",
        "summary": "The table of user-tracked positions that live alongside the auto-generated lab rows.",
        "detail": (
            "Manual positions let you add your own rows to the review workspace. Use them for discretionary trades, paper trades, or ideas you want to watch outside the generated signal set."
        ),
    },
    "created_at": {
        "section": "manual_positions",
        "label": "Created at",
        "summary": "When the manual row was added to the workspace.",
        "detail": (
            "Created at is the timestamp for when you recorded the manual position in the UI."
        ),
    },
    "source_signal_date": {
        "section": "manual_positions",
        "label": "Source signal date",
        "summary": "The original signal date associated with the row, if you know it.",
        "detail": (
            "Source signal date helps keep a manual position linked back to the original idea or recommendation date."
        ),
    },
    "capital": {
        "section": "manual_positions",
        "label": "Capital",
        "summary": "The manual notional capital assigned to that row.",
        "detail": (
            "Capital determines the notional size of the manual position for current-value and PnL calculations."
        ),
    },
    "current_return_pct": {
        "section": "manual_positions",
        "label": "Current return %",
        "summary": "The marked-to-market percentage return of the manual position.",
        "detail": (
            "Current return % shows how the manual position is performing relative to the recorded entry price."
        ),
    },
    "distance_to_stop_pct": {
        "section": "manual_positions",
        "label": "Distance to stop %",
        "summary": "How close the current price is to the stop, expressed as a percentage.",
        "detail": (
            "Distance to stop % is useful for prioritizing attention. Smaller values mean the position is closer to the protective stop."
        ),
    },
    "note": {
        "section": "manual_positions",
        "label": "Note",
        "summary": "Free-form context about the manual position.",
        "detail": (
            "Use Note for reminders, discretionary context, or anything that makes the row easier to interpret later."
        ),
    },
}


TABLE_HELP_KEYS: dict[str, dict[str, str]] = {
    "pattern_weights": {
        "Pattern": "pattern_family",
        "Score /100": "pattern_score_100",
        "Weight /30": "pattern_weight_30",
        "Count": "count",
        "Win %": "win_rate",
        "Loss %": "loss_rate",
        "Edge pp": "edge_pp",
    },
    "quick_check": {
        "Item": "quick_check",
        "Status": "status",
    },
    "past_results": {
        "signal_date": "source_signal_date",
        "outcome": "outcome",
        "return_pct": "return_pct",
        "exit_date": "exit_date",
    },
    "trade_records": {
        "signal_date": "source_signal_date",
        "ticker": "overview",
        "pattern_family": "pattern_family",
        "pattern": "pattern",
        "entry_price": "entry_price",
        "qty": "qty",
        "invested": "invested",
        "target_price": "target_price",
        "stop_price": "stop_price",
        "latest_close": "latest_close",
        "current_value": "current_value",
        "pnl": "pnl",
        "return_pct": "return_pct",
        "days_held": "days_held",
        "exit_date": "exit_date",
        "status": "status",
        "signal_score": "heuristic_score",
        "score_pattern": "score_pattern",
        "pattern_bonus": "pattern_bonus",
        "stock_rs20": "stock_rs20",
        "stock_rs50": "stock_rs50",
        "rs_bonus": "rs_bonus",
        "enhancer_bonus": "enhancer_bonus",
    },
    "manual_positions": {
        "created_at": "created_at",
        "source_signal_date": "source_signal_date",
        "ticker": "overview",
        "pattern": "pattern",
        "entry_price": "entry_price",
        "stop_price": "stop_price",
        "latest_close": "latest_close",
        "capital": "capital",
        "current_value": "current_value",
        "pnl": "pnl",
        "current_return_pct": "current_return_pct",
        "distance_to_stop_pct": "distance_to_stop_pct",
        "status": "status",
        "note": "note",
    },
}


def get_help_item(help_key: str) -> dict[str, str]:
    return HELP_ITEMS.get(help_key, HELP_ITEMS["overview"])


def _set_docs_focus(help_key: str) -> None:
    item = get_help_item(help_key)
    st.session_state["docs_focus_key"] = help_key
    st.session_state["docs_focus_section"] = item["section"]
    st.session_state["mode"] = "Documentation"


def _ensure_help_chip_css() -> None:
    if st.session_state.get("_docs_chip_css_v6_loaded"):
        return
    st.session_state["_docs_chip_css_v6_loaded"] = True
    st.markdown(
        """
        <style>
        /* Plain HTML anchor chip — zero Streamlit button theming involved.
           Sky-blue translucent ring: visible on both dark and light backgrounds. */
        a.docs-help-chip {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 1.1rem;
            height: 1.1rem;
            border-radius: 50%;
            background: rgba(56, 189, 248, 0.13);
            border: 1.5px solid rgba(56, 189, 248, 0.55);
            color: #38bdf8 !important;
            font-size: 0.64rem;
            font-weight: 900;
            line-height: 1;
            text-decoration: none !important;
            cursor: pointer;
            vertical-align: middle;
            flex-shrink: 0;
            font-family: ui-sans-serif, system-ui, sans-serif;
            letter-spacing: -0.01em;
            transition: background 0.15s, border-color 0.15s, box-shadow 0.15s;
        }
        a.docs-help-chip:hover,
        a.docs-help-chip:focus {
            background: rgba(56, 189, 248, 0.28);
            border-color: #38bdf8;
            color: #7dd3fc !important;
            box-shadow: 0 0 0 2px rgba(56, 189, 248, 0.2);
            text-decoration: none !important;
            outline: none;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def handle_help_query_param() -> None:
    """Call once at top of app — intercepts ?help=<key> clicks from HTML chips."""
    focus = st.query_params.get("help", "")
    if focus and focus in HELP_ITEMS:
        # Remove the param so it doesn't persist across reruns
        params = dict(st.query_params)
        params.pop("help", None)
        st.query_params.from_dict(params)
        _set_docs_focus(focus)
        st.rerun()


def render_help_button(help_key: str, *, key: str, tooltip: str | None = None) -> None:
    _ensure_help_chip_css()
    item = get_help_item(help_key)
    title_text = (tooltip or f"{item['label']}: {item['summary']}").replace('"', "&quot;").replace("'", "&#39;")
    st.markdown(
        f'<a class="docs-help-chip" href="?help={help_key}" title="{title_text}">?</a>',
        unsafe_allow_html=True,
    )


def render_heading_with_help(
    title: str,
    help_key: str,
    *,
    key: str,
    level: int = 3,
    caption: str | None = None,
) -> None:
    left, right = st.columns([0.94, 0.06])
    with left:
        st.markdown(f"{'#' * int(level)} {title}")
    with right:
        render_help_button(help_key, key=key)
    if caption:
        st.caption(caption)


def render_caption_with_help(text: str, help_key: str, *, key: str) -> None:
    left, right = st.columns([0.9, 0.1], gap="small")
    with left:
        st.markdown(
            f"<div style='font-size:0.78rem; color:var(--heading-color); font-weight:700; line-height:1.15;'>{text}</div>",
            unsafe_allow_html=True,
        )
    with right:
        render_help_button(help_key, key=key)


def table_help_map(table_name: str, columns: Iterable[str]) -> dict[str, str]:
    table_map = TABLE_HELP_KEYS.get(table_name, {})
    return {column: table_map[column] for column in columns if column in table_map}


def build_dataframe_column_config(column_help_keys: dict[str, str]) -> dict[str, object]:
    config: dict[str, object] = {}
    for column, help_key in column_help_keys.items():
        item = get_help_item(help_key)
        config[column] = st.column_config.Column(column, help=item["summary"])
    return config


def render_table_help_glossary(
    title: str,
    column_help_keys: dict[str, str],
    *,
    key_prefix: str,
    expanded: bool = False,
) -> None:
    if not column_help_keys:
        return

    with st.expander(f"{title} column help", expanded=expanded):
        for idx, (column, help_key) in enumerate(column_help_keys.items()):
            item = get_help_item(help_key)
            left, right = st.columns([0.88, 0.12])
            with left:
                st.markdown(f"**{column}**  \\n+{item['summary']}")
            with right:
                render_help_button(help_key, key=f"{key_prefix}_{idx}")


def _pattern_family_lines() -> list[str]:
    return [
        "**A**: breakout-style setups that rely on strength through a prior reference zone.",
        "**B**: alternate breakout or continuation behavior with a different trigger shape.",
        "**C**: MACD-oriented setups that look for momentum confirmation.",
        "**D**: RSI-oriented setups that look for strength and reset behavior.",
        "**E**: Bollinger-style setups that use band structure or compression clues.",
        "**F**: VWAP-oriented setups that care about price behavior around intraday or anchored reference value.",
        "**G**: VCP-style contraction and breakout setups.",
    ]


def render_documentation_page() -> None:
    focus_key = str(st.session_state.get("docs_focus_key", "") or "").strip()
    focus_item = get_help_item(focus_key) if focus_key else None
    focus_section = str(st.session_state.get("docs_focus_section", "") or "").strip()

    st.markdown(
        (
            "<div class='hero'>"
            "<div class='hero-title'>Documentation</div>"
            "<div class='hero-sub'>Use the question-mark links across the app to jump here for deeper explanations.</div>"
            "</div>"
        ),
        unsafe_allow_html=True,
    )

    if focus_item:
        st.info(f"Jumped here from: {focus_item['label']}")
        st.markdown("### Focus topic")
        st.markdown(f"**{focus_item['label']}**")
        st.markdown(focus_item["detail"])

    section_cols = st.columns(4)
    for idx, section_id in enumerate(SECTION_COPY.keys()):
        with section_cols[idx % 4]:
            if st.button(SECTION_COPY[section_id]["title"], key=f"docs_nav_{section_id}", width="stretch"):
                st.session_state["docs_focus_section"] = section_id
                st.session_state["docs_focus_key"] = ""
                st.rerun()

    grouped_items: dict[str, list[tuple[str, dict[str, str]]]] = defaultdict(list)
    for help_key, item in HELP_ITEMS.items():
        grouped_items[item["section"]].append((help_key, item))

    for section_id, copy in SECTION_COPY.items():
        expanded = section_id == focus_section or bool(focus_item and focus_item["section"] == section_id)
        with st.expander(copy["title"], expanded=expanded):
            st.markdown(copy["intro"])
            if section_id == "patterns":
                for line in _pattern_family_lines():
                    st.markdown(f"- {line}")
            items = sorted(grouped_items.get(section_id, []), key=lambda pair: pair[1]["label"])
            for help_key, item in items:
                st.markdown(f"#### {item['label']}")
                st.markdown(item["detail"])
                if focus_key == help_key:
                    st.caption("This is the topic you most recently opened from the live UI.")